from typing import Tuple
from ellphi import FloatArray
from ._solver_python import TangencyResult

def is_available() -> bool: ...
def linalg_kind() -> str | None: ...
def backend_version() -> str | None: ...
def tangency(
    pcoef: FloatArray,
    qcoef: FloatArray,
    *,
    method: str,
    bracket: Tuple[float, float],
    x0: float | None,
    hybrid_bracket_maxiter: int,
    hybrid_newton_maxiter: int,
    failsafe: bool,
) -> TangencyResult: ...
def pdist_tangency(coef: FloatArray) -> FloatArray: ...
def has_pdist_tangency_grad() -> bool: ...
def pdist_tangency_grad(
    coef: FloatArray,
) -> Tuple[FloatArray, FloatArray, FloatArray]: ...
