from __future__ import annotations
from typing import IO, Any, Iterable, Iterator, Sequence, Tuple, overload
import numpy as np
import numpy.typing as npt
from matplotlib import pyplot as plt
from . import solver
from .geometry import unpack_single_conic

__all__ = ["EllipseCloud"]

class EllipseCloud:
    coef: np.ndarray
    def __init__(self, coef: Iterable[npt.ArrayLike]) -> None: ...
    @classmethod
    def from_param(cls, params: Iterable[npt.ArrayLike]) -> EllipseCloud: ...
    @property
    def n_ell(self) -> int: ...
    @property
    def dim(self) -> int: ...
    def __len__(self) -> int: ...
    @overload
    def __getitem__(self, key: int) -> np.ndarray: ...
    @overload
    def __getitem__(self, key: slice | Sequence[int]) -> EllipseCloud: ...
    def __iter__(self) -> Iterator[np.ndarray]: ...
    def plot(
        self,
        ids: Sequence[int] | None = None,
        ax: plt.Axes | None = None,
        scale: float = 1.0,
        **kwgs,
    ) -> plt.Axes: ...
    def pdist_tangency(
        self, *, parallel: bool = True, n_jobs: int | None = -1, backend: str = "auto"
    ): ...
    def write_coef(self, f: IO[str]) -> None: ...
    def as_ellcat(self) -> Any: ...
