import matplotlib.pyplot as plt
import numpy
from _typeshed import Incomplete
from dataclasses import dataclass, field
from typing import Iterator, Sequence

__all__ = ['ellipse_cloud', 'EllipseCloud', 'LocalCov']

@dataclass
class EllipseCloud:
    coef: numpy.ndarray
    mean: numpy.ndarray
    cov: numpy.ndarray
    k: int
    nbd: numpy.ndarray
    n: int = field(init=False)
    n_dim: int = field(init=False)
    def __post_init__(self) -> None: ...
    def __len__(self) -> int: ...
    def __iter__(self) -> Iterator[numpy.ndarray]: ...
    def __getitem__(self, idx) -> numpy.ndarray: ...
    def plot(self, ids: Sequence[int] | None = None, ax: plt.Axes | None = None, scale: float = 1.0, **kwgs) -> plt.Axes: ...
    def pdist_tangency(self, *, parallel: bool = True, n_jobs: int | None = -1, backend: str = 'auto'): ...
    @classmethod
    def from_point_cloud(cls, X: numpy.ndarray, *, method: str = 'local_cov', rescaling: str = 'none', **kwgs) -> EllipseCloud: ...
    @classmethod
    def from_local_cov(cls, X: numpy.ndarray, *, k: int = 5) -> EllipseCloud: ...
    def rescale(self, *, method: str = 'median') -> float: ...

ellipse_cloud: Incomplete

@dataclass(frozen=True)
class LocalCov:
    k: int = ...
    def __call__(self, X: numpy.ndarray) -> EllipseCloud: ...
