import numpy

__all__ = ['unit_vector', 'axes_from_cov', 'coef_from_axes', 'coef_from_cov', 'pack_conic', 'unpack_conic', 'unpack_single_conic', 'infer_dim_from_coef_length']

def unit_vector(theta: float) -> numpy.ndarray: ...
def axes_from_cov(cov: numpy.ndarray, /, *, scale: float = 1.0): ...
def infer_dim_from_coef_length(length: int) -> int: ...
def pack_conic(matrices: numpy.ndarray, linear: numpy.ndarray, constant: numpy.ndarray) -> numpy.ndarray: ...
def unpack_conic(coef: numpy.ndarray) -> tuple[numpy.ndarray, numpy.ndarray, numpy.ndarray]: ...
def unpack_single_conic(coef: numpy.ndarray) -> tuple[numpy.ndarray, numpy.ndarray, numpy.ndarray]: ...
def coef_from_axes(X: float, r0: float, r1: float, theta: float) -> numpy.ndarray: ...
def coef_from_cov(X: numpy.ndarray, cov: numpy.ndarray, /, *, scale: float = 1.0) -> numpy.ndarray: ...
