# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: CI

on:
  push:
    branches: [ main ]
  pull_request:        # 全 PR

permissions:
  contents: read       # テストに read 権限のみで十分

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.10", "3.11"]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        cache: "pip"

    # -- Poetry ------------------------------------------------------
    - name: Install Poetry
      run: pip install --upgrade poetry

    - name: Cache Poetry env
      uses: actions/cache@v3
      with:
        path: ~/.cache/pypoetry
        key: ${{ runner.os }}-poetry-${{ hashFiles('pyproject.toml') }}

    - name: Install project (dev extras)
      run: poetry install --with dev

    # -- Lint / Format ----------------------------------------------
    - name: flake8
      run: poetry run flake8 src tests

    - name: black check
      run: poetry run black --check src tests

    # -- Type-check --------------------------------------------------
    - name: mypy
      run: poetry run mypy src

    # -- Tests & coverage -------------------------------------------
    - name: pytest
      run: poetry run pytest --cov=ellphi -q
